openmrs/openmrs-esm-fast-data-entry-app

- src/forms-page/FormsPage.tsx
- src/forms-table/FormsTable.tsx
- src/hooks/useGetAllForms.ts
This implements a frontend filter for which forms are shown to a user based on which edit privileges they have
Completes TFS 319173
Screenshots show new (count) display. Super user shows all 75 forms, user with some roles and privileges shows 49 available forms.
> (feat) Filter forms by privileges

- src/forms-app-menu-link.tsx
This PR renames the app menu link component from `OfflineToolsAppMenuLink` to `FormsAppMenuLink`.
> (fix) Rename app menu link component

- src/config-schema.ts
- src/group-form-entry-workflow/GroupSessionWorkspace.tsx
- [n/a] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
This injects group session meta data fields into the form payload. Group session metadata concept UUIDs are configurable through config schema
Metadata fields are
- Session Name
- Session Date
- Practitioner Name
- Session Notes
Metadata field UUIDs are specified here -> https://github.com/openmrs/openmrs-distro-referenceapplication/blob/3.x/distro/configuration/concepts/group_session_meta-core_demo.csv
> Posts Group Session Metadata

- src/form-entry-workflow/styles.scss
Sets form to `text-align: left` 
Before:
After:
[TFS-346410](https://tfs.ext.icrc.org/ICRCCollection/Pearlii/_sprints/backlog/Mekom/Pearlii/Application/EMR/Mekom/2022/2022%20Sprint%2019?workitem=346410)
> (fix) Left align form labels

- src/forms-page/forms-table/FormsTable.tsx
Sets up the DataTable table headers such that only the Form Name row is sortable. The Actions row doesn't benefit from being sortable because of the kind of content it contains. Also renames a couple of variables.
> Before
> After
> (fix) Only Form Name row should be sortable

- src/FormBootstrap.tsx
Form rendered within the extension slot using openmrs-ngx-formentry wasn't properly updating after the patient was changed unless a manual browse refresh was triggered. With this fix, when the patient is changed, the slot containing the form is forced to be refreshed.
> (fix) Trigger formentry slot refresh

- src/context/GroupFormWorkflowContext.tsx
- src/context/GroupFormWorkflowReducer.ts
- src/group-form-entry-workflow/GroupSessionWorkspace.tsx
On a group session, each patient encounter is now created wrapped in each own visit (one distinct visit per patient). Flow and outcome is the same as it was implemented for individual session (https://github.com/openmrs/openmrs-esm-fast-data-entry-app/pull/43):
1. The encounter is 1st created detached from any visit (same as before)
2. On the handleEncounterCreate callback, a visit creation with the same date is triggered
3. Because the visit was created async, after creation, the encounter is then updated so that it belongs to the visit
When a session is in progress, the user will be able two switch between the forms for the patients belonging to the group. When the form is saved the 1st time, a visit is created to wrap the encounter (flow above). When the user return to an already saved …
> (feat) Groups Session Visit

- src/context/FormWorkflowContext.tsx
- src/context/FormWorkflowReducer.ts
- src/context/GroupFormWorkflowContext.tsx
- src/context/GroupFormWorkflowReducer.ts
- src/forms-page/FormsPage.tsx
Workflow was being saved on browser localStorage independently of the logged user meaning that, if a user logged out and another user logged in using the same browser, the workflow from 1st user would be loaded and overwritten.
With this PR, the workflow is saved on localStorage having the userId as a suffix so that workflow is properly loaded/saved per user.
> (feat) Save and load distinct workflows per logged user

- src/hooks/useForm.ts
- src/hooks/useGetAllForms.ts
- src/hooks/useGetEncounter.ts
- src/hooks/useGetSystemSetting.ts
- src/hooks/usePostEndpoint.ts
- src/hooks/useSearchEndpoint.ts
- src/hooks/useStartVisit.ts
Change all instances of the hard-coded API base URL '/ws/rest/v1/' to use the restBaseUrl variable instead. To enhances maintainability and flexibility of the API base URL configuration.
N/A
https://openmrs.atlassian.net/browse/O3-2815
> (refactor) Replace usages of /ws/rest/v1 with restBaseUrl

- src/FormBootstrap.tsx
This pull request addresses the issue of inconsistent dates between session date and encounter date. Inconsistent dates can lead to confusion and errors in the system, impacting the reliability and usability of the application. The fix ensures that session dates and encounter dates are synchronized properly, resolving any discrepancies and promoting data integrity.
The proposed fix ensures that the encounter date aligns with the session date, providing users with the expected behavior.
Session date
Encounter date:
The reason the input is disabled is because there is a parallel development in the form-entry-app which, if the date is pre-filled, makes no sense to change it.
More details [here](https://github.com/openmrs/openmrs-esm-patient-chart/pull/1747).
Thanks,
> (fix) Inconsistent dates between session date and encounter date

- src/config-schema.ts
- src/context/GroupFormWorkflowContext.tsx
- src/context/GroupFormWorkflowReducer.ts
- src/group-form-entry-workflow/GroupSessionWorkspace.tsx
- src/group-form-entry-workflow/SessionDetailsForm.tsx
Added functionality to enhance group session data storage by incorporating session and cohort identifiers. This includes additional fields for cohort name, cohortId, and sessionUuId. These new fields complement existing ones such as sessionName, sessionDate, and sessionNotes, providing a more comprehensive dataset for group sessions.
Thanks,
CC: @ibacher
> (feat) Add session and cohort identifiers for group sessions

- src/add-group-modal/AddGroupModal.tsx
- src/context/GroupFormWorkflowReducer.ts
- src/group-form-entry-workflow/SessionDetailsForm.tsx
- src/group-form-entry-workflow/attendance-table/AttendanceTable.tsx
- src/group-form-entry-workflow/group-search-header/GroupSearchHeader.tsx
When creating a group, no specific order for the patients is explicitly defined. Initially, the order established during the creation is maintained for the first session. However, for subsequent sessions, the order of patients changes, following the sequence in which they are retrieved from the database.
With this development the order of the patients within a group will always be alphabetical.
> (feat) Patient name sorting

- src/FormBootstrap.tsx
- src/context/GroupFormWorkflowReducer.ts
This PR solves the problem of form duplication on fast data entry:
Steps to replicate:
1. After creating your session move to the last Patient.
3. Press the button "Save form". (The form will not appear)
5. then press the button "Save & Complete".
7. The last patient form will be duplicated.
> Fixed last patient form duplication

- src/hooks/useSpecificQuestions.ts
- src/types.ts
- [] My work includes tests or is validated by existing tests.
This PR introduces support for providing a filtered list of specific answers in configurations. Instead of fetching all possible answers for a question, the system now allows explicitly defining and serving a static set of answers.
When the `answers` property is specified, only the IDs listed will be considered as possible answers.
```
{
"answers": [
"concept-uuid-1",
"concept-uuid-2"
]
}
```
Concepts labels are still fetched dynamically, requiring no static configuration.
N/A
N/A
Thanks,
> (feat) Support for static specific answers

- jest.config.json
- package.json
- src/declarations.d.ts
- tsconfig.json
- yarn.lock
Carbon version updated to v1.71.0
https://github.com/user-attachments/assets/1d592432-4305-48f7-9fd4-347e36a9c864
https://openmrs.atlassian.net/browse/O3-4255
> (chore) O3-4255: Bump @carbon/react to v1.17.0

- src/group-form-entry-workflow/GroupSessionWorkspace.tsx
This PR fixes an issue in the `handleEncounterCreate` function where concepts from `activeSessionMeta` could be redundantly added to the `obs` payload, leading to duplicates. The function now checks if a concept from `activeSessionMeta` already exists in `payload.obs` before adding it.
> (fix) Avoid adding duplicate session obs to obs payload

- src/CompleteModal.tsx
This PR addresses an issue where the "Save & Complete" button becomes unresponsive if the user accidentally clicks outside the confirmation pop-up. Previously, users had to refresh the page to proceed.
- Open an form/start a session and fill it out.
- If we miss the button complete by mistake and we click above the pop-up disappears
- The Save & Complete button becomes irresponsive
Thanks,
> (fix) Prevent "Save & Complete" button from becoming unresponsive

- src/add-group-modal/AddGroupModal.tsx
- src/config-schema.ts
- src/form-entry-workflow/FormEntryWorkflow.tsx
- src/form-entry-workflow/patient-search-header/PatienMismatchedLocationModal.tsx
- src/form-entry-workflow/patient-search-header/PatientSearchHeader.tsx
- src/hooks/location-tag.resource.ts
- translations/en.json
- translations/es.json
- translations/fr.json
Displays a warning modal if the selected HSU location does not match the current session location.
Allows the user to confirm or cancel their selection.
> (feat) Confirmation modal when selecting patient outside session location

- src/add-group-modal/AddGroupModal.tsx
- src/form-entry-workflow/patient-search-header/PatienMismatchedLocationModal.tsx
This PR addresses an issue where the prompt for a patient location mismatch was not functioning correctly when managing session patient groups.
> (fix) Correct patient location mismatch prompt behavior in group management

- jest.config.json
- package.json
- src/add-group-modal/AddGroupModal.tsx
- src/forms-page/FormsPage.tsx
- src/forms-page/forms-table/FormsTable.tsx
- src/group-form-entry-workflow/SessionDetailsForm.tsx
- src/group-form-entry-workflow/attendance-table/AttendanceTable.tsx
- src/group-form-entry-workflow/group-search/CompactGroupResults.tsx
- src/group-form-entry-workflow/group-search/CompactGroupSearch.tsx
- src/group-form-entry-workflow/group-search/compact-group-result.scss
- yarn.lock
Should fix up the few issues we need to address to get the auto-update workflow back to working here.
> (chore) O3-4745: Fix failing dependency auto-update CI workflow

- README.md
Proceeding from [Fix FDE for RFE forms instances](https://github.com/openmrs/openmrs-esm-fast-data-entry-app/pull/115), this PR updates the README.md to highlight the flexibility of FDE with both Angular and React form engines and adds detailed documentation for pre-filled/specific questions.
> (docs): Document FDE integration with RFE/AFE and pre-filled questions
