package.json
It's a workaround for now until I get tests setup on this repo
=> (patch) Pass with no coverage

.github/workflows/node.js.yml, src/index.ts
This will add a job for deploying fast-data-entry-app to digital ocean cdn, and updating the refapp importmap
=> Adds FDE esm to refapp

.github/workflows/node.js.yml
Directory structure of fast-data-entry-app is not yet controlled by turbo / lerna.... this PR makes the deploy step reference actual dist folder for FDE-app
=> References actual directory

README.md, docs/configuring-form-categories.md
Makes README links valid markdown
none
none
none
=> (chore) Fix README links

src/context/FormWorkflowContext.tsx, src/context/FormWorkflowReducer.ts, src/form-entry-workflow/FormEntryWorkflow.tsx, src/forms-page/FormsPage.tsx, src/forms-table/FormsTable.tsx, translations/en.json
This saves the workflow sessions in local storage and allows them to be reloaded again
Necessary foundation for [TFS-306894](https://tfs.ext.icrc.org/ICRCCollection/Pearlii/_sprints/backlog/Mekom/Pearlii/Application/EMR/Mekom/2022/2022%20Sprint%2014?workitem=306894)
=> (feat) Form workflow state persistence

src/context/FormWorkflowContext.tsx, src/context/FormWorkflowReducer.ts, src/form-entry-workflow/FormEntryWorkflow.tsx, src/form-entry-workflow/styles.scss, src/patient-card/PatientCard.tsx, src/patient-card/styles.scss, translations/en.json
Implements cancel and save buttons for fast data entry workflow
https://user-images.githubusercontent.com/5445264/183656282-407e800f-ab1f-4a8f-bcdd-7bb8c38bf09d.mov
TFS-327692
=> (feat) Workflow Submit and Cancel Buttons

package.json, yarn.lock
Removes unused packages and follows better peer dependency syntax
Thanks @manuelroemer for inspiration and work from [this PR.](https://github.com/icrc/openmrs-esm-patient-grid/pull/2)
=> (chore) Better peer dependency syntax, Remove Cruft

package.json, yarn.lock
=> (chore) add semver as a devDependency

.github/workflows/ci.yml
=> Fixing pre-release

.github/workflows/ci.yml
=> Fix/pre release - add git user for ci pipeline

.github/workflows/ci.yml
Updating digital ocean import map is no longer necessary
=> (chore) Removes update importmap step

.github/workflows/ci.yml
=> (chore) fix deployment task

translations/fr.json
This pull request adds a French label for the App Menu link in the project. With this update, users who prefer to use the French language will be able to have the menu link translated.
Thanks,
=> (fix) Add French Label for App Menu Link

src/form-entry-workflow/styles.scss, src/group-form-entry-workflow/styles.scss, src/patient-card/styles.scss
=> (enhc) Reviewed styling

jest.config.json, src/hooks/useGetPatient.ts, yarn.lock
=> (chore) Bump @openmrs/esm-framework

package.json, src/index.ts, src/routes.json, yarn.lock
Updates to using routes.json and core 5.0.0
=> (BREAKING) Migrate esm-fast-data-entry to use routes.json

.tx/config
=> (chore) Migrate to newer transifex version

src/add-group-modal/AddGroupModal.tsx, src/group-form-entry-workflow/group-search-header/GroupSearchHeader.tsx
This update addresses an issue where users were unable to add new members to an existing group due to an error encountered while attempting to sort patients by their name during editing.
=> (fix) Resolve issue preventing addition of patients to existing groups

src/add-group-modal/AddGroupModal.tsx, src/config-schema.ts
This pull request adds functionality to include cohort type in group sessions. It enables the categorization of group sessions, providing better organization and management of group activities.
The default cohort type is the already existing `System List` cohort type. 
Additionally, it enables customization of the fast data entry cohort type by allowing each distribution to provide it in the configuration.
_There is no UI changes, just a reference to where to create the group_
Thanks,
=> (chore) Add cohort type in group sessions

yarn.lock
This PR bumps openmrs core and framework.
=> (chore): Bump Openmrs core and framework

package.json
This PR cuts a minor release. The draft changelog:
* (feat) Maintain form order according to cfg settings by @icrc-psousa in https://github.com/openmrs/openmrs-esm-fast-data-entry-app/pull/90
* (fix) Avoid adding duplicate session obs to obs payload by @icrc-jofrancisco in https://github.com/openmrs/openmrs-esm-fast-data-entry-app/pull/89
* (test) O3-2413: Setup playwright for automated tests in Fast Data Entry App  by @dilankavishka in https://github.com/openmrs/openmrs-esm-fast-data-entry-app/pull/88
=> (chore): Release v1.2.0

src/add-group-modal/AddGroupModal.tsx
Ensures that, when a cohort is updated or created, the start date field of each cohort member is properly set as the current date and never left blank.
=> (fix) Update start date field on cohort update

package.json
Cuts a minor release of Fast Data Entry that includes new features and backwards compatible bug fixes:
* (feat) Confirmation modal when selecting patient outside session location by @icrc-psousa in https://github.com/openmrs/openmrs-esm-fast-data-entry-app/pull/105
* (feat) Add configuration option to disable group sessions for specific form by @icrc-jofrancisco in https://github.com/openmrs/openmrs-esm-fast-data-entry-app/pull/104
* (fix) Resolve patient duplication triggered by page focus event by @icrc-psousa in https://github.com/openmrs/openmrs-esm-fast-data-entry-app/pull/107
* (fix) Correct patient location mismatch prompt behavior in group management by @icrc-psousa in https://github.com/openmrs/openmrs-esm-fast-data-entry-app/pull/106
* (fix) Update start date field on cohort …
=> (chore) Release v1.3.0

src/config-schema.ts
With this PR, we are removing implementation-specific configuration schema defaults (e.g., ICRC forms, Distress Scales).
**Before**
**After**
=> (fix) Remove implementation-specific config
